### PR TITLE
remove verbose log msg from NodeGroupService

### PR DESCRIPTION
**Pull request by georgechrysanthakopoulos**
see https://github.com/vmware/xenon/commit/9f89a27508821116a6f4c6fcd303861485c87e2a

fyi @ttddyy @toliaqat @asafka

### CODE REVIEW

**Comment by toliaqat** [comment]
We have sometimes used these log messages to detect possible conflict in
the node group state between nodes. It has helped to find which
node is not able to agree on the version of the node-group state with other nodes.

**Comment by georgechrysanthakopoulos** [comment]
any updates on this?

**Comment by asafka** [comment]
I don't find this message valuable either. @toliaqat do you find this specific message helpful?

**Comment by toliaqat** [comment]
These logs are annoying most of the time but were the only way to debug/detect gossip problems in past.

**Comment by toliaqat** [comment]
I suggest that we go the route of fixing this off-by-one version between node status entries.

**Pull request closed without merging**
