### PR TITLE
Pull request for variance tracking in time series stats

### PR DESCRIPTION
**Pull request by georgechrysanthakopoulos**

### CODE REVIEW

**Comment by georgechrysanthakopoulos** [comment]
@asafka @toliaqat @ylui @ttddyy fyi.
relevant commit is
https://github.com/vmware/xenon/pull/18/commits/c224e8224fba639b23d33e8a61b8114ddb6363c2

**Comment by ttddyy** [comment]
@georgechrysanthakopoulos 
Thanks for the PR.
I just cherry picked the commit c224e82 and created an internal review.

**Comment by ttddyy** [comment]
FYI: Since this PR is from your master branch, when you push more commits to your master, they will be reflected to this PR. So, I suggest making a dedicated branch in github for each PR.

**Comment by ttddyy** [comment]
merged to master: 1a1e5b1e9d7f5ef89159361e7aba9826e4e8677d

**Comment by georgechrysanthakopoulos** [comment]
thank you @ttddyy

**Pull request closed without merging**
